### ISSUE TITLE
Trying the 0.1.6.2 release...

### ISSUE THREAD

**Issue by ftctechnh** [dmssargent/AppInstaller#3]
When I try to drag an APK file onto the UI it doesn't appear in the list.  Also, I tried to browse and select the APK file, but when I did so it crashed.  I've attached a screen shot and also the .tmp file.

Note that I changed the suffix from ".tmp" to ".txt" so GitHub would allow me to attach the file.

![image](https://cloud.githubusercontent.com/assets/12596789/17410785/3c179172-5a43-11e6-9e47-6ce9f03e7a97.png)

[tmpB0D1.txt](https://github.com/dmssargent/AppInstaller/files/402175/tmpB0D1.txt)

**Comment by dmssargent** [comment]
Exception Details

```
Length cannot be less than zero.

Parameter name: length at System.String.Substring(Int32 startIndex, Int32 length)
   at APKInstaller.AndroidTools.MostLikelyAndroidSdk(String[] paths)
   at APKInstaller.AndroidTools.MostLikelyAndroidSdk(String path)
   at APKInstaller.AndroidTools.SetupAdb()
   at APKInstaller.AndroidTools.SetupIfPossible()
   at APKInstaller.AndroidTools.RunAapt(String args, Boolean redirectStdOut)
   at APKInstaller.AndroidTools.PackageName(String apkFile)
   at APKInstaller.Installer.ValidateFile(String path, Boolean notifyUser)
```

**Comment by dmssargent** [comment]
@ftctechnh I built a debug build with a patch applied. Does the new build work correctly for you?
[AppInstaller.zip](https://github.com/dmssargent/AppInstaller/files/403099/AppInstaller.zip)

**Comment by dmssargent** [comment]
@ftctechnh does the issue still exist in [v0.1.7.0](https://github.com/dmssargent/AppInstaller/releases/tag/v0.1.7.0-beta)?
